var AudioFile=function(a){this._file=a;this._audioData=this._audioBuffer=null};AudioFile.audioContext=null;AudioFile.prototype.getArrayBuffer=function(a){var b=new FileReader;b.onload=function(){a(b.result)};b.onError=function(){a(null)};b.readAsArrayBuffer(this._file)};
AudioFile.prototype.getAudioBuffer=function(a){if(this._audioBuffer)a(this._audioBuffer);else{var b=this;this.getArrayBuffer(function(c){c?(window.AudioContext=window.AudioContext||window.webkitAudioContext,AudioFile.audioContext=AudioFile.audioContext||new AudioContext,AudioFile.audioContext.decodeAudioData(c,function(c){b._audioBuffer=c;a(c)},function(){a(null)})):a(null)})}};
AudioFile.prototype.getAudioData=function(a){this._audioData?a(this._audioData,this._audioBuffer.sampleRate):this.getAudioBuffer(function(b){if(b)if(0==b.numberOfChannels)a(null);else{var c=this._audioBuffer.getChannelData(0);if(2<=b.numberOfChannels)for(var e=b.getChannelData(1),d=0;d<c.length;d++)c[d]=(c[d]+e[d])/2;this._audioData=c;a(c,b.sampleRate)}else a(null)}.bind(this))};var TapCounter=function(){this.reset()};TapCounter.prototype.reset=function(){this._tapCount=0;this._tapTimestamps=[];this._tapBPM=0};TapCounter.prototype.tap=function(){this._tapCount=0;this._tapTimestamps.push((new Date).getTime());var a=0;_.each(this._tapTimestamps,function(b,c){0!=c&&(a+=b-this._tapTimestamps[c-1])}.bind(this));this._tapBPM=0==a?0:60*(1/(a/this._tapTimestamps.length/1E3))};TapCounter.prototype.getBPM=function(){return this._tapBPM};var App=function(){this._$progressBarContainer=$(".progress");this._$progressBar=$(".progress-bar");this._$result=$(".result-box .result");this._$fileSelector=$(".file-selector");this._$tapButton=$(".tap-button");this._tapCounter=new TapCounter;this.initJumbotron();this.setActionBoxState(App.ACTION_BOX_STATE_IDLE);var a=new Worker(DEBUG?"js/BPMWorker.js":"js/packed/worker.js");a.onmessage=function(a){"bpmResult"==a.data.type?(this.updateProgressBar(100),this.showResult(a.data.bpm)):"progress"==a.data.type&&
this.updateProgressBar(a.data.progress)}.bind(this);var b=function(){this.setActionBoxState(App.ACTION_BOX_STATE_PROCESSING);this.updateProgressBar(0)}.bind(this),c=function(c){b();this._tapCounter.reset();(new AudioFile(c)).getAudioData(function(b,c){b?a.postMessage({type:"command",commandType:"getBPM",channelData:b,sampleRate:c}):this.setActionBoxState(App.ACTION_BOX_STATE_LOAD_ERROR)}.bind(this))}.bind(this),e=document.querySelector('[type="file"]');e.addEventListener("change",function(a){(a=e.files[0])&&
c(a)});this._$fileSelector.click(function(){e.value="";e.click()});this._$tapButton.click(function(){this._tapCounter.tap();this.setActionBoxState(App.ACTION_BOX_STATE_TAPPING);this.updateBPM(this._tapCounter.getBPM())}.bind(this))};App.FILE_SELECTOR_CLASSES_TO_REMOVE="btn-primary btn-default btn-danger";App.ACTION_BOX_STATE_IDLE="IDLE";App.ACTION_BOX_STATE_PROCESSING="PROCESSING";App.ACTION_BOX_STATE_TAPPING="TAPPING";App.ACTION_BOX_STATE_DONE="DONE";
App.prototype.initJumbotron=function(){var a=$(".jumbotron"),b=function(){var b=Math.round(($(window).height()-a.outerHeight())/2);a.get(0).style.setProperty("margin-top",b+"px","important")};$(window).resize(b);b()};
App.prototype.setActionBoxState=function(a){var b=function(a,b,d){this._$fileSelector.removeClass(App.FILE_SELECTOR_CLASSES_TO_REMOVE).addClass(a).text(b).attr("disabled",d);return this._$fileSelector}.bind(this);switch(a){case App.ACTION_BOX_STATE_IDLE:b("btn-primary","Select a song",!1);this._$progressBarContainer.hide();this._$result.hide();this._$tapButton.attr("disabled",!1);break;case App.ACTION_BOX_STATE_LOAD_ERROR:b("btn-danger","Can't load audio file",!1);this._$progressBarContainer.hide();
this._$result.hide();this._$tapButton.attr("disabled",!0);break;case App.ACTION_BOX_STATE_PROCESSING:b("btn-default","Processing...",!0);this._$progressBarContainer.show();this._$result.hide();this._$tapButton.attr("disabled",!0);break;case App.ACTION_BOX_STATE_TAPPING:this._$result.show();b("btn-primary","Select a song",!1);this._$progressBarContainer.hide();this._$tapButton.attr("disabled",!1);break;case App.ACTION_BOX_STATE_DONE:b("btn-primary","Select a song",!1),this._$progressBarContainer.hide(),
this._$result.show(),this._$tapButton.attr("disabled",!1)}};App.prototype.updateProgressBar=function(a){this._$progressBar.width(a+"%")};App.prototype.updateBPM=function(a){this._$result.text(a.toFixed(1)+" BPM")};App.prototype.showResult=function(a){this.updateBPM(a);this.setActionBoxState(App.ACTION_BOX_STATE_DONE)};
